### PR TITLE
Add pid in all fuse ops

### PR DESCRIPTION
**Pull request by xinmeigui-db**
Add pid in all fuse ops

### CODE REVIEW

**Comment by xinmeigui-db** [comment]
Hi @stapelberg , would appreciate some comments & feedback!

**Comment by stapelberg** [comment]
Adding the caller process id to all ops sounds okay to me in general, but:

1.  Why do you need to disable writeback caching for the pid to become available?
2. Your pull request seems to contain a lot of unrelated commits? Can you clean it up please? (rebase)

Thanks,

**Comment by xinmeigui-db** [comment]
> Adding the caller process id to all ops sounds okay to me in general, but:
> 
> 1. Why do you need to disable writeback caching for the pid to become available?
> 2. Your pull request seems to contain a lot of unrelated commits? Can you clean it up please? (rebase)
> 
> Thanks,

Thanks for the review!

1. We disabled the writeback cache because when the write comes from the writeback cache, there is no pid associated with that (the test may be flaky as a result).
2. Rebased!

**Comment by dotslash** [comment]
> Your pull request seems to contain a lot of unrelated commits? Can you clean it up please? (rebase)
If the PR is squash-merged, then this is not relevant. right?

**Comment by stapelberg** [comment]
> If the PR is squash-merged, then this is not relevant. right?

Cleanly separated commits also make the review easier, no matter if they end up in the git history or not :)

**Pull request merged**
