### PR TITLE
Calculate pageSize and bufSize at run-time

### PR DESCRIPTION
**Pull request by gaul**
ARM-based macOS uses 16 KB pages instead of 4 KB.  Fixes
GoogleCloudPlatform/gcsfuse#548.

### CODE REVIEW

**Comment by gaul** [comment]
Unfortunately I don't have an ARM-based Mac to test this on.

**Comment by grisaitis** [comment]
This fixes gcsfuse for me on my MacBook Pro (13-inch, M1, 2020), as I discuss in this comment: https://github.com/GoogleCloudPlatform/gcsfuse/issues/548#issuecomment-897045626

**Review by stapelberg — APPROVED** [review]

**Comment by stapelberg** [comment]
> This fixes gcsfuse for me on my MacBook Pro (13-inch, M1, 2020), as I discuss in this comment: [GoogleCloudPlatform/gcsfuse#548 (comment)](https://github.com/GoogleCloudPlatform/gcsfuse/issues/548#issuecomment-897045626)

Thanks for confirming! Now merged

**Comment by hongjun0619** [comment]
@gaul

**Comment by gaul** [comment]
> @gaul AWS r6g.2xlarge is arm system type,you can create a testing instance to test

I believe that Linux on ARM uses 4 KiB pages.  Only macOS on ARM uses 16 KiB pages.

**Comment by stapelberg** [comment]
> I believe that Linux on ARM uses 4 KiB pages. Only macOS on ARM uses 16 KiB pages.

Yes, this is my understanding, too.

**Comment by hongjun0619** [comment]
@gaul  @stapelberg 
Then I want to know what needs to be done on linux arm to use goofys？

Regrads,

**Comment by gaul** [comment]
Please use the goofys bug tracker for support requests with that software.

**Comment by hongjun0619** [comment]
@gaul 
So sorry,what is  bug tracker?

**Comment by gaul** [comment]
https://github.com/kahing/goofys/issues

**Comment by hongjun0619** [comment]
Sorry,I don't find analogous issue,your means is that goofys supports Linux ARM system in fact?

**Comment by gaul** [comment]
This project is not goofys.  We cannot support their issues here.

**Pull request merged**
