### PR TITLE
Support OSXFUSE 3.x, fall back to 2.x if needed

### PR DESCRIPTION
**Pull request by zbiljic**
Also supports custom bundled OSXFUSE installs.

The homebrew cask osxfuse version is now 3.5.0: https://github.com/caskroom/homebrew-cask/blob/master/Casks/osxfuse.rb#L2.

This code is basically transferred from bazil.org/fuse.

### CODE REVIEW

**Comment by zbiljic** [comment]
First, I would like to apologize for delayed response.
Second, you are completly right in wanting to have references for these changes; stellar documentation is why I chose this library in the first place. I must have spend two days going through the commits just to verify everything that you are asking.

As for the answers:

1. All the variables are indeed needed.
2. Yes. They have changed the osxfuse file system library paths and options, even during development of osxfuse 3.x.
3. At first `OSXFUSEPaths` were internal, but someone might (at some point) have the need for custom osxfuse build, and this way it is easy to do so.

I will attempt to provide updated pull request as soon as I am able to.
Also, if you think some things should be changed, I won't mind to do so.

**Comment by jacobsa** [comment]
Thanks! Sorry for _my_ slow response; I've been away on holiday. As for what needs to be done here:

1. Could you please make all of the new symbols unexported again? We can export them later if a need truly arises. I would rather have the library just do the right thing.
2. It sounds like you did a bunch of research on this. Could you please link (in the code comments) to your sources?

It would be best if you could do these as new commits in the pull request rather than overwriting the existing one. I may wind up pulling this as-is if osxfuse 3 support becomes urgent, so would like to be able to cleanly make these fixes afterward.

**Comment by zbiljic** [comment]
Just as I started to commit changes, you already finished.
Sorry again, this was really the only free time I've had in previous weeks.

**Comment by jacobsa** [comment]
No worries, thanks for the fix. I'm still very interested in getting references from you if you have them.

**Pull request merged**
