### PR TITLE
Notifyfunc impl and add mount subtype

### PR DESCRIPTION
**Pull request by inevity**
impl fuse notify func 
add fuse subtype mountconfig

### CODE REVIEW

**Comment by jacobsa** [comment]
Could you please

1. Add some description of what this is, with background context about why you'd want it and how it works, to both the commits and the pull requests?

2. Add some documentation to the code, for at least the functions in package fuse?

At a glance I have no idea what this is.

(It also sounds like the two commits are for two orthogonal things? If so, please send two pull requests.)

**Comment by inevity** [comment]
About subtype ,see pull request https://github.com/jacobsa/fuse/pull/34

**Comment by inevity** [comment]
About impl fuse notify func ,sed pull request https://github.com/jacobsa/fuse/pull/35

**Comment by stapelberg** [comment]
[helping out with maintenance, doing first round of pull request triage]
Closing this one in favor of #34 and #35

**Pull request closed without merging**
