### PR TITLE
Switch from Travis CI to GitHub Actions

### LINKED ISSUE #99: Switch from Travis to GitHub Actions
Our tests don’t even run on Travis anymore. We should really switch to GitHub Actions. Help welcome :)

### PR DESCRIPTION
**Pull request by tetsuok**
Fixes #99.

### CODE REVIEW

**Comment by tetsuok** [comment]
It seems this repo isn't configured to run actions yet. See [doc](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository) for how to set up.

**Comment by stapelberg** [comment]
Thanks for your PR! Did you test in a separate repository that it works? Can you link to a GitHub Actions run that worked please?

**Comment by tetsuok** [comment]
@stapelberg Here it is: https://github.com/tetsuok/fuse/pull/1/checks

**Comment by stapelberg** [comment]
Thanks very much!

**Comment by tetsuok** [comment]
@stapelberg Running tests in Linux in this repo hangs for some reason (interestingly, the tests [passed](https://github.com/tetsuok/fuse/runs/4131678407?check_suite_focus=true) in my fork). Just created a follow-up PR #113 to disable running tests in CI. Apparently, it takes time to investigate the root cause and fix the issue. Until we figure it out, I think we should just use CI just to build go binaries.

**Pull request merged**
